name: mp3
description: A new Flutter project.
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter

  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/flashcards.json
